# Generated by Django 5.2.8 on 2026-09-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_leaverequest_handover_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('HOLIDAY', 'Office Leave/Holiday'), ('OFFICE_EVENT', 'Office Event'), ('MEETING', 'Scheduled Meeting')], default='OFFICE_EVENT', max_length=15),
        ),
    ]
